package mbot;

// IB imports
import com.ib.client.Contract;
import com.ib.client.EClientSocket;

//
// This class represents all jobs relating to the MktStk datafeed
//
public class CassandraJob extends Job
{

    //
    // Job defs
    //
    public static final int JOB_INVALID = 0;
    public static final int JOB_START_FEED = 1;
    public static final int JOB_STOP_FEED = 2;

    private int jobType = JOB_INVALID;


}